### ISSUE TITLE
Rotating objects invisible/non interact-able

### ISSUE THREAD

**Issue by Caznix** [DM-Earth/create-fabric-dme-edition#9] opened 2023-10-11 19:01 UTC
### Describe the Bug

When you create a contraption such as a windmill, mechanical bearing, gantry, etc they become invisible untill you stop them.

### Reproduction Steps

1.Install sodium 0.5.3 
2.Install create-fabric-0.5.1-d-build.9+mc1.20.1
3. create a rotating contraption
...

### Expected Result

Contraption to appear rotating until stopped

### Screenshots and Videos

https://github.com/DM-Earth/create-fabric-dme-edition/assets/131402549/bf850ce3-d789-4087-9991-cda893241de5

### Operating System

Linux (fedora 38)

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

occurs both with and without indium

**Comment by TexBlock** [comment] 2023-10-12 07:06
Duplicate of #8

**Closed as not planned** 2023-10-12 07:06 UTC
Labels: bug
